## Please follow the below structure while attempting the hackathon, make sure to submit only one jupyter file with all the models, and you can always mention your best model by giving it the header as 'Best Model'.

## Please make sure to maintain the clarity of analysis in the notebook with proper headers and inisghts/inferences, so that it can be interpretable 


## Please follow the same format as mentioned below, as you will be evaluated basis on your Jupyter Notebook for L2 selection.

## Importing Necessary Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

## 1 Data Cleaning

In this section you can do all the Data cleaning part of all necessary imputations and treatments

In [3]:
data1 = pd.read_csv("Data_Train.csv")
data2 = pd.read_csv("Data_Test.csv")

In [4]:
data1.head(2)

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee,Loan/No Loan
0,95074,421802,II,>10yrs,Vfied,633600.00000,MOR??AGE,0,0,GLENDALE NISSAN,...,fully paid,California,17,58598.00000,3 years,31216.05000,debt consolidation,I,0.00000,0
1,134131,3964312,IV,7yrs,Source Verified,85483.20000,REN?,0,0,Business Teacher,...,whole,NC,15,18924.00000,5 years,11660.49000,debt consolidation,I,0.00000,0

In [5]:
data2.head(2)

,ID,Asst_Reg,GGGrade,Experience,Validation,Yearly Income,Home Status,Unpaid 2 years,Already Defaulted,Designation,...,Sub GGGrade,File Status,State,Account Open,Total Unpaid CL,Duration,Unpaid Amount,Reason,Claim Type,Due Fee
0,198980,1773284,II,2yrs,Source Verified,140800.00000,OWN,0,0,processor,...,17,fully paid,California,23,33532.00000,3 years,15755.94000,major purchase,I,0.00000
1,167688,5298273,II,>10yrs,Vfied,146080.00000,MOR??AGE,0,0,Speech Language Pathologist,...,19,whole,Florida,17,149234.00000,5 years,68237.55000,debt consolidation,I,0.00000

In [6]:
data1.dtypes

ID                       int64
Asst_Reg                 int64
GGGrade                 object
Experience              object
Validation              object
Yearly Income          float64
Home Status             object
Unpaid 2 years           int64
Already Defaulted        int64
Designation             object
Debt to Income         float64
Postal Code            float64
Lend Amount            float64
Deprecatory Records      int64
Interest Charged       float64
Usage Rate             float64
Inquiries                int64
Present Balance        float64
Gross Collection       float64
Sub GGGrade              int64
File Status             object
State                   object
Account Open             int64
Total Unpaid CL        float64
Duration                object
Unpaid Amount          float64
Reason                  object
Claim Type              object
Due Fee                float64
Loan/No Loan             int64
dtype: object

In [7]:
data2.dtypes

ID                       int64
Asst_Reg                 int64
GGGrade                 object
Experience              object
Validation              object
Yearly Income          float64
Home Status             object
Unpaid 2 years           int64
Already Defaulted        int64
Designation             object
Debt to Income         float64
Postal Code            float64
Lend Amount            float64
Deprecatory Records      int64
Interest Charged       float64
Usage Rate             float64
Inquiries                int64
Present Balance        float64
Gross Collection       float64
Sub GGGrade              int64
File Status             object
State                   object
Account Open             int64
Total Unpaid CL        float64
Duration                object
Unpaid Amount          float64
Reason                  object
Claim Type              object
Due Fee                float64
dtype: object

In [8]:
# Checking whether dataframe columns are equal or not
dataframes = [data1, data2]

# Checking all dataframe columns, whether they are equal or not
if all([len(dataframes[0].columns.intersection(df.columns)) 
      == dataframes[0].shape[1] for df in dataframes]) == True:
    print("The dataframes have same column names")
else:
    print("The dataframes does not have same column names")

The dataframes does not have same column names

In [9]:
# Finding column differences
tr_cols = data1.columns
te_cols = data2.columns
print(tr_cols.difference(te_cols))
print(te_cols.difference(tr_cols))

Index(['Loan/No Loan'], dtype='object')
Index([], dtype='object')

In [10]:
data1.isnull().sum()

ID                        0
Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation            1414
Debt to Income         3489
Postal Code            1389
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        4186
Duration                  0
Unpaid Amount          4852
Reason                    0
Claim Type                0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [11]:
data2.isnull().sum()

ID                        0
Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          2425
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation             586
Debt to Income         1511
Postal Code             611
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        1814
Duration                  0
Unpaid Amount          2069
Reason                    0
Claim Type                0
Due Fee                   0
dtype: int64

In [12]:
data1.shape

(87500, 30)

In [13]:
data2.shape

(37500, 29)

In [14]:
# Checking set of values in all columns
for i in data1.columns:
    print("\nValues for ", i)
    print(data1[i].unique())

Values for  ID
[ 95074 134131  92602 ... 102153 115343 104968]

Values for  Asst_Reg
[ 421802 3964312 4247560 ... 2624710 5966919 6637289]

Values for  GGGrade
['II' 'IV' 'III' 'V' 'VII' 'VI' 'I']

Values for  Experience
['>10yrs' '7yrs' '<1yr' '2yrs' '1yrs' '4yrs' '9yrs' '6yrs' '5yrs' '8yrs'
 '3yrs']

Values for  Validation
['Vfied' 'Source Verified' 'Not Vfied']

Values for  Yearly Income
[633600.    85483.2   79200.   ... 510398.24 154191.84  90423.52]

Values for  Home Status
['MOR??AGE' 'REN?' 'OWN' 'OTHER' 'NONE']

Values for  Unpaid 2 years
[ 0  4  2  1  3 11  5  6  7  9 12  8 10 18 16 15 13 14]

Values for  Already Defaulted
[0 1 2 6 5 4 3]

Values for  Designation
['GLENDALE NISSAN' 'Business Teacher' 'driver' ... 'Interface Coordinator'
 'PARTS CLERK' 'Outside sales rep']

Values for  Debt to Income
[12.5496  9.0048 24.9144 ... 65.7216  0.4032 63.6888]

Values for  Postal Code
[91300. 27400. 32800.  7000. 70800. 77000. 92100.  6000. 92500. 78500.
 95900. 49400. 97200. 72200. 11900. 91900. 59100. 28300. 80800. 72900.
 45000. 27500. 87100. 55000. 30300.    nan 11700. 75200. 20800. 32500.
 35400. 28000. 29700. 17700. 95800. 85700. 84400. 16800. 44700.  2100.
 76000. 85300. 78700. 20100. 27200. 48500. 77300. 45200. 61800. 71400.
 18700. 23400. 11200. 13000. 36500. 92600. 29400. 10000. 11300. 53500.
 95100. 92000. 89400. 96700. 12000. 91700.  2900. 70000. 11600. 48200.
 18000.  8900. 38000. 28200. 33100. 99200. 12500. 33000. 73000. 33300.
 90000.  5700. 37900. 94100. 89000. 74000. 47100. 33400. 99500. 32900.
 43700. 38100. 29600.  6400. 21200. 55100. 46400. 94500. 33800. 10400.
 11000. 69300. 36600. 68000. 48100. 94600. 78200.  3800. 20000. 78000.
 10700. 89500. 11500. 93200.  8000. 14500. 90200. 56000. 92800. 97000.
 76100. 63800. 10500. 10300. 20700. 29000. 79900. 48800. 75000. 43900.
 16600. 26300. 38600. 27300. 92400. 30100. 72500. 14400. 49600. 44100.
 45800. 34600. 32700. 90800. 23100. 32400. 71700. 93000. 46300. 60400.
 38300. 85000. 92700. 55300. 84100.  2000. 98900. 60100. 95600. 43100.
 85200.  7600. 22500. 80100. 16000. 33600. 89100. 35000. 40900. 33900.
  6200. 23200. 14800. 44900. 30000. 32200. 72700. 15200. 60000. 98100.
 60700. 18100. 31000. 70100. 98300. 17000. 46100. 22600. 17800. 70400.
 35700. 76500. 80900. 76200. 77400. 41000. 43000. 94000. 98000. 97500.
 37200. 74900. 44600. 19000.  6500. 81500. 11100. 40200. 32100. 44000.
 64100. 35800. 24500. 39400. 28100. 86300. 75100. 28700. 55400.  8800.
  8500. 66200. 24400. 93500. 49200. 46900. 26000. 14100. 74100. 60600.
 22000. 72000. 74600. 93300. 81000. 19700. 45300. 53100. 25500. 49500.
 47300. 64000. 62200. 44300. 84000. 63000. 61300. 67500. 47200. 29200.
 19100. 89800. 80000. 34400. 45100. 18900. 80200. 33500. 58100. 61600.
 26500. 91200. 48000. 99000. 79700. 45400. 77500. 87300. 47500. 43500.
 91600. 79100. 95000. 27000.  1800. 30200. 49800. 57700.  7700. 10600.
 92300. 99600. 12300. 24800.  3400. 37600. 21800. 34200. 19500. 61100.
 68100. 27600. 49000. 66700. 11400. 78100. 65700. 71300. 15000. 30700.
 39100. 43200. 63300. 44500. 31300. 36100. 32600. 84600.  2700. 46200.
 13800.  6700. 54000. 79400. 76300. 31600. 12900.  8200. 27700. 72400.
 53200. 19400. 13700. 73100. 98400. 37300. 65200. 54900. 44400. 70500.
 14200. 48300. 10100. 42200.  7800. 42300. 75900. 39000. 59700. 62400.
 22200. 67400. 73400.  2800. 73500. 93400. 17500. 66000. 40500. 96800.
  2300. 54500. 62300. 77700.  5400. 55900. 31500.  6800. 35200.  3200.
 98500. 25100. 93900. 15500. 14700. 37400. 33700. 48600. 60900.  6900.
 74800. 57300. 22300. 30500.  1900. 61000. 63100.  6600. 29500.  7300.
 49300. 12100. 18300.  8700. 23000. 39500. 67200. 15400. 78600. 15600.
 31400. 90700. 97400. 17300. 60300. 86400. 60500. 54600. 34100. 88200.
 80600. 24700. 64800.  1500. 80500. 30800. 73800. 71100. 25400.  2500.
 31200. 24900. 53900. 53000. 86000. 29300. 95400. 27800. 98600. 21000.
 94900. 75400. 40000. 31700. 62700. 45500. 92200. 91500. 95300. 43600.
 13500. 19800. 36000. 56700. 84300. 40300. 37100. 99900. 23600. 66600.
 16100.  7500. 24100. 95200. 16300. 94400. 42000. 84500. 59000. 12600.
 42700. 56400.  5000. 27900. 82900. 30600. 67300. 78400. 21700. 14600.
 47700. 22400. 91000. 46500. 44200. 22100. 47600. 11800. 85100.  3000.
 46700. 34700. 98200. 43400. 19900. 18400. 35600. 94300. 72100. 32300.
 17900. 68400. 22700. 81200. 65600.  1200. 39800. 17100. 95700. 20600.
 77200. 97700.  1000.  6100. 19600. 40400. 28800. 36800. 93600. 99300.
  8100. 37700. 31900. 67600. 21400. 71000. 37000. 18600. 32000. 18500.
 47000. 45600. 72600. 53700. 64700.  7400.  1400. 23300. 67800. 46000.
  1700. 54100. 36300. 28400. 20900. 64500. 75600. 75300. 26700. 67000.
 46600. 15300. 16900. 61500. 44800. 62600. 13900. 21100. 91100. 24000.
 65800. 39300. 98800. 59900. 34900. 93700. 13200.  8600. 79000. 35100.
 53400. 54800. 35900.  1300. 77900. 16200. 76700. 43300. 13600.  3700.
  4100. 82700. 46800. 47900. 63900. 13400.  1600. 79200. 15100. 91400.
 56500. 38700. 12800. 64400. 80300. 62500. 27100. 85600. 67700. 49700.
 23500. 71900. 61700. 19300. 28500. 80700. 63500. 49100. 74500. 81300.
 86500. 82600. 90600. 66100. 97300. 24200. 67100. 90300. 68500. 88100.
 56300. 85500. 17400. 54400. 90500. 15900. 48400. 97100. 61200. 13100.
 28600. 80400. 37800. 88000. 36200. 38500. 74700.  2600.  2400. 70700.
  3500. 29100. 14000. 49900. 76800. 96000. 94800. 22900.  6300. 95500.
 73600. 55700. 65500. 17600. 65000. 56600. 57000. 75800. 99700. 93100.
 26200. 29900. 91800. 10900. 57400. 87500. 25300. 71200. 89700. 30900.
 23800. 65100. 75700. 82200. 82000. 41100. 30400. 17200.  5300. 81600.
 82400. 97800. 81100. 84700.  3300. 73700. 61400. 14900. 97900. 16700.
 82800.  7900. 71800. 25800. 54200. 88300.  8400. 16500. 79600. 87000.
 57200. 29800. 77800. 60800. 58600.  8300. 36700.  9000. 26100. 82300.
 76400. 66500. 47800. 64600. 76900. 67900. 63700. 89300. 38800. 78300.
 54700. 23700. 87400.  3100. 31800. 10200. 18800. 39200.  7200. 66800.
  7100. 59400. 59800. 41700. 62900. 96200. 39700. 63400. 24600. 45700.
 14300. 12700. 21600. 21900. 70300.  4200. 62800. 25200. 78900.  1100.
 42400. 25000. 59600. 83100. 54300. 24300. 70600. 72300. 65300. 81400.
 41200. 59200. 40100. 83000. 78800. 58500. 57100. 77600. 10800. 59500.
 59300. 57600. 58200. 12200. 55600. 26400. 38900. 55800. 76600. 65400.
 16400. 74400. 79500. 38400. 97600.  4900. 56200. 28900. 90400. 58000.
 96100. 15800. 35500. 22800. 99800. 71600. 79800. 94700. 18200. 75500.
 48700. 79300. 25700. 48900. 42100. 62000. 42500. 85900. 38200. 47400.
 42600. 58700. 12400. 68900. 74300. 68800.  5800. 56100. 90100. 21500.
 40700. 41600. 41500. 13300. 53800. 26800. 50000. 43800.  5100. 25900.
 36400. 99100. 26600.  4700.  4000.  5200. 61900. 57500. 25600.  4600.
 60200. 33200. 58800. 82500. 63600. 31100. 39600. 68600. 66400. 23900.
 96500. 15700.  5600. 68700.  2200. 36900. 41800.  4400. 40600. 72800.
  4300.  5900. 68300.  3900. 87700. 83600.  9400. 94200. 69100. 40800.
  4800. 41300. 69000. 52700. 73900.  9100. 88400.  3600. 34300. 58300.
  9600. 41400.  4500. 77100. 87800. 83800.]

Values for  Lend Amount
[42023.25 38133.   17100.   ... 56857.5  52026.75 52796.25]

Values for  Deprecatory Records
[ 0  1  2  5  4  3  7  6  9  8 10 12 86 11 13 16 22 15]

Values for  Interest Charged
[15.39  9.94 22.35 ... 24.13  9.95 22.24]

Values for  Usage Rate
[ 88.924 102.856  60.372 ... 185.76  176.3   222.74 ]

Values for  Inquiries
[3 0 1 2 4 5 6 8]

Values for  Present Balance
[607161.9  269234.06  22476.53 ... 102811.88  14584.11  10445.85]

Values for  Gross Collection
[   0.    469.78 1093.23 ... 3093.41  795.77  691.56]

Values for  Sub GGGrade
[19 30 25 22 32 24 21 43 31 28 40 14 15 17 16 18 33 23 26 27 20 38 13 34
 29 37 11 12 42 36 35 41 39 45 44]

Values for  File Status
['fully paid' 'whole']

Values for  State
['California' 'NC' 'Florida' 'NewJersey' 'LA' 'TX' 'CT' 'MI' 'OR' 'AR'
 'Newyork' 'MT' 'CO' 'Ohio' 'NM' 'MN' 'GA' 'WA' 'Maryland' 'AL' 'SC' 'PA'
 'AZ' 'UT' 'MA' 'VA' 'IL' 'WI' 'NV' 'HI' 'RI' 'TN' 'OK' 'VT' 'IN' 'AK'
 'MO' 'NE' 'NH' 'DC' 'WV' 'MS' 'KY' 'KS' 'DE' 'ND' 'SD' 'WY' 'ME']

Values for  Account Open
[17 15  7  9 10 11 26  6 14  8 13 27 12 16 39 19  5 20 18 30 34 21 24  3
 29 25 23 32 28 22 44  4 68 83 31 38 33 36 37 35 43 54 48 42  2 40 63 41
 80 49 46 45 50 56 52 51 57 65 47]

Values for  Total Unpaid CL

[ 58598.    18924.    15604.   ... 495510.    27456.4  105859.86]

Values for  Duration
['3 years' '5 years']

Values for  Unpaid Amount
[31216.05 11660.49  5637.87 ... 82601.55 82056.06 52676.55]

Values for  Reason
['debt  consolidation' 'major  purchase' 'other' 'credit  card' 'car'
 'home  improvement' 'small  business' 'moving' 'vacation' 'medical'
 'wedding' 'house' 'renewable  energy']

Values for  Claim Type
['I' 'J']

Values for  Due Fee
[0.00000000e+00 1.50000000e+01 1.50000001e+01 2.81200000e+01
 5.97600000e+01 5.06200000e+01 4.31200000e+01 3.38800000e+01
 1.88400000e+01 3.99582903e+01 2.82625006e+01 3.81600000e+01
 2.57500000e+01 2.33100000e+01 2.54300000e+01 3.16100000e+01
 1.76300000e+01 4.67400000e+01 2.15600000e+01 4.10200000e+01
 2.16300000e+01 1.84000000e+01 4.92700000e+01 1.72100000e+01
 2.71100000e+01 1.63700000e+01 3.67200000e+01 3.62400000e+01
 9.94000000e+01 3.00000000e+01 2.11900000e+01 3.76045674e+01
 5.40700000e+01 1.56000000e+01 4.40700000e+01 3.38500000e+01
 1.47100000e+01 1.99200000e+01 3.35000000e+01 4.02100000e+01
 6.38807300e+01 3.72100000e+01 1.83100000e+01 3.27300000e+01
 3.08500000e+01 2.98000000e+01 2.44700000e+01 2.68000000e+01
 1.16750000e+02 1.51000000e+01 1.76100000e+01 1.49985323e+01
 8.16200000e+01 3.66900000e+01 5.03300000e+01 1.58800000e+01
 4.48800000e+01 1.87900000e+01 3.24400000e+01 2.27500000e+01
 1.65000000e+01 2.89300000e+01 2.00000000e+01 3.38600000e+01
 4.18800000e+01 2.38600000e+01 2.86200000e+01 1.49937900e+01
 1.98200000e+01 4.66100000e+01 1.52400000e+01 1.98700000e+01
 2.57000000e+01 2.02955005e+01 2.61100000e+01 2.06800000e+01
 1.80200000e+01 2.28000000e+01 1.66500000e+01 2.74800000e+01
 2.92200000e+01 2.01300000e+01 4.47200000e+01 2.35300000e+01
 2.87100000e+01 4.45700000e+01 1.86000000e+01 1.75700000e+01
 2.99576559e+01 1.49696505e+01 2.04100000e+01 1.80000000e+01
 2.62200000e+01 2.86700000e+01 4.00000000e+01 3.95100000e+01
 4.15500000e+01 1.74400000e+01 1.83400000e+01 5.52600000e+01
 5.04300000e+01 2.23200000e+01 1.68700000e+01 1.07820000e+02
 9.33900000e+01 2.53900000e+01 4.40300000e+01 4.53200000e+01
 3.86200000e+01 1.51100000e+01 1.00000000e-02 2.80200000e+01
 2.43700000e+01 2.73800000e+01 1.17480000e+02 3.21100000e+01
 2.78900000e+01 2.43400000e+01 2.20100000e+01 4.98000000e+01
 8.14500000e+01 3.88600000e+01 9.46680496e+01 2.23000000e+01
 2.06900000e+01 1.73300000e+01 4.50000000e+01 2.50900000e+01
 2.51600000e+01 3.53700000e+01 2.85300000e+01 4.65600000e+01
 2.76512360e+01 2.50200000e+01 3.42200000e+01 6.52200000e+01
 7.38400000e+01 5.89600000e+01 4.34800000e+01 3.68400000e+01
 1.56885106e+01 1.89825100e+01 3.17000000e+01 4.46700000e+01
 3.41800000e+01 2.70500000e+01 1.49761676e+01 2.64600000e+01
 4.05800000e+01 4.32800000e+01 3.87400000e+01 1.95600000e+01
 9.62500000e+01 7.50000000e+01 1.71000000e+01 4.45100000e+01
 4.95300000e+01 1.59855800e+01 1.68473200e+01 8.64775000e+01
 2.58900000e+01 2.15000000e+01 1.88500000e+01 3.21500000e+01
 1.88100000e+01 4.85100000e+01 1.91500000e+01 4.23800000e+01
 2.07200000e+01 2.19700000e+01 4.41100000e+01 2.90200000e+01
 2.84599999e+01 1.72992499e+01 4.00600000e+01 4.03500000e+01
 2.32600000e+01 3.69600000e+01 2.99090005e+01 4.53300000e+01
 2.03100000e+01 2.92900000e+01 1.49495933e+01 2.45800000e+01
 5.08500000e+01 4.29200000e+01 2.02100000e+01 2.38200000e+01
 3.23400000e+01 3.01400000e+01 2.80500000e+01 3.76800000e+01
 5.79100000e+01 3.04700000e+01 3.17500000e+01 5.03200000e+01
 2.06400000e+01 2.05000000e+01 2.42100000e+01 1.92400000e+01
 3.20300000e+01 1.69300000e+01 2.09800000e+01 1.54200000e+01
 4.51300000e+01 1.67900000e+01 1.99300000e+01 2.21900000e+01
 2.72400000e+01 2.33160000e+01 2.40400000e+01 1.51600000e+01
 2.99829407e+01 3.80200000e+01 1.52100000e+01 1.66400000e+01
 2.81800000e+01 8.49200000e+01 1.58900000e+01 3.44600000e+01
 2.99513185e+01 8.09690300e+01 4.98700000e+01 3.06000000e+01
 4.49600000e+01 2.35700000e+01 1.67200000e+01 3.64000000e+01
 5.64600000e+01 1.52200000e+01 2.07000000e+01 1.65300000e+01
 1.59400000e+01 2.45500000e+01 1.49984826e+01 3.31800000e+01
 2.31400000e+01 8.20500000e+01 6.59300000e+01 8.58500000e+01
 7.67300000e+01 3.15200000e+01 3.21200000e+01 9.35800000e+01
 3.37100000e+01 2.53200000e+01 5.89300000e+01 4.27700000e+01
 2.73000000e+01 2.01500000e+01 3.00800000e+01 1.96400000e+01
 3.19000000e+01 2.56900000e+01 1.64200000e+01 3.31300000e+01
 3.39800000e+01 2.03900000e+01 4.43000000e+01 2.79100000e+01
 1.49879150e+01 2.14200000e+01 2.29800000e+01 1.62500000e+01
 3.34000000e+01 1.74800000e+01 3.33500000e+01 1.70100000e+01
 2.22300000e+01 1.67100000e+01 6.23800000e+01 1.49861265e+01
 4.10700000e+01 3.90200000e+01 2.56280062e+01 1.75300000e+01
 2.93219957e+01 1.67200000e+01 2.03485000e+01 7.65800000e+01
 1.73892700e+01 3.40100000e+01 1.49880643e+01 1.76500000e+01
 3.06300000e+01 8.27300000e+01 2.73700000e+01 2.06000000e+01
 3.27800000e+01 1.83500000e+01 2.47700000e+01 3.37500000e+01
 4.88800000e+01 1.56700000e+01 3.77800000e+01 1.55400000e+01
 1.82300000e+01 1.59300000e+01 3.53000000e+01 2.60500000e+01
 1.56500000e+01 5.64100000e+01 2.34800000e+01 1.49824462e+01
 1.90900000e+01 6.28800000e+01 1.71900000e+01 3.25100000e+01
 1.63600000e+01 4.79800000e+01 2.74900000e+01 2.95100000e+01
 3.96900000e+01 1.66800000e+01 7.96100000e+01 4.13100000e+01
 2.24000000e+01 2.35600000e+01 7.59300000e+01 2.45500001e+01
 1.71300000e+01 7.42500000e+01 1.21858500e+02 1.64000000e+01
 3.14700000e+01 1.87700000e+01 4.52132389e+01 3.77200000e+01
 2.60700000e+01 3.17900000e+01 2.62500000e+01 2.16200000e+01
 1.76700000e+01 1.55600000e+01 6.31600000e+01 1.70000000e+01
 4.69600000e+01 1.94300000e+01 1.69050000e+02 1.56329948e+01
 2.15100000e+01 3.81000000e+01 2.23600000e+01 2.07100000e+01
 3.15900000e+01 4.86800000e+01 3.86400000e+01 2.37900000e+01
 3.64300000e+01 2.32900001e+01 1.12600000e+02 3.98979908e+01
 2.54200000e+01 3.31900000e+01 1.72600000e+01 5.19900000e+01
 2.03700000e+01 2.74700000e+01 8.77200000e+01 1.95900000e+01
 3.83000000e+01 2.37500000e+01 6.26800000e+01 3.66800000e+01
 4.59000000e+01 2.05100000e+01 2.04400000e+01 6.99200000e+01
 2.42509745e+01 3.55700000e+01 4.22400000e+01 2.94300000e+01
 1.55700000e+01 2.95400000e+01 2.55300000e+01 9.03600000e+01
 6.37400000e+01 4.46800000e+01 1.80800000e+01 4.55900000e+01
 5.50700000e+01 4.44500000e+01 4.69000000e+01 6.19400000e+01
 2.88800000e+01 1.75900000e+01 2.87800000e+01 2.04950051e+01
 3.31200000e+01 2.72799800e+01 1.49845225e+01 8.70000000e-01
 3.49600000e+01 6.06400000e+01 3.17200000e+01 4.90300000e+01
 3.44000000e+01 2.24200000e+01 1.97700000e+01 2.33000000e+01
 3.55900000e+01 2.95000000e+01 1.67000000e+01 2.54000000e+01
 4.52800000e+01 4.07100000e+01 2.24500000e+01 4.17900000e+01
 4.69200000e+01 2.47400000e+01 3.14500000e+01 4.68400000e+01
 2.20000000e+01 2.41100000e+01 1.50000000e+01 2.59300000e+01
 2.69021951e+01 1.49621193e+01 2.40700000e+01 3.40200000e+01
 1.90300000e+01 3.22100000e+01 3.40982542e+01 1.52600000e+01
 3.14200000e+01 2.64900000e+01 1.59800000e+01 5.01200000e+01
 2.09100000e+01 2.58100000e+01 5.04500000e+01 1.02480000e+02
 2.39200000e+01 4.95600000e+01 1.86100000e+01 3.48200000e+01
 2.84400000e+01 4.58800000e+01 4.56600000e+01 2.03200000e+01
 1.49931347e+01 3.52300000e+01 2.76900000e+01 1.62700000e+01
 1.55200000e+01 2.33400000e+01 1.90400000e+01 2.13200000e+01
 2.59631703e+01 1.82400000e+01 4.05400000e+01 2.68700000e+01
 2.74500000e+01 5.43700000e+01 6.11900000e+01 3.68900000e+01
 4.87800000e+01 3.23000000e+01 5.29500000e+01 3.06900000e+01
 3.61900000e+01 2.49600000e+01 3.29900000e+01 1.58700000e+01
 3.32100000e+01 3.83078176e+01 3.30000000e+01 2.23100000e+01
 2.32400000e+01 6.28900000e+01 2.42500000e+01 3.92700000e+01
 4.56846300e+01 3.08300000e+01 5.96300000e+01 1.67500000e+01
 5.14800000e+01 5.32800000e+01 2.05400000e+01 4.17200000e+01
 2.07600000e+01 1.49924847e+01 6.66800000e+01 6.85600000e+01
 1.49502600e+01 2.08600000e+01 2.15800000e+01 1.83300000e+01
 1.49863425e+01 2.83000000e+01 3.43400000e+01 2.83600000e+01
 2.96200000e+01 3.34500000e+01 3.06400000e+01 2.06500000e+01
 3.19400000e+01 3.44900000e+01 5.44528200e+01 6.50300000e+01
 7.54800000e+01 3.52900000e+01 3.69100000e+01 3.65800000e+01
 2.35800000e+01 2.71400000e+01 3.16500000e+01 3.60200000e+01
 1.30950000e+02 1.03440000e+02 3.48900000e+01 1.49473584e+01
 1.25780000e+02 1.53095000e+01 3.11900000e+01 2.20700000e+01
 2.22800000e+01 1.57500000e+01 2.50100000e+01 4.02605000e+01
 2.79700000e+01 5.55400000e+01 2.21700000e+01 1.71700000e+01
 2.71600000e+01 2.18400000e+01 4.77300000e+01 4.98900000e+01
 4.67000000e+01 2.58400000e+01 3.10600000e+01 2.69792500e+01
 3.99300000e+01 2.99798600e+01 1.52900000e+01 2.22400000e+01
 1.83800000e+01 1.92700000e+01 6.00000000e+01 1.57700000e+01
 1.64600000e+01 1.89200000e+01 7.52700000e+01 1.53400000e+01
 3.03200000e+01 7.84800000e+01 1.84100000e+01 2.83100000e+01
 2.22600000e+01 5.39100000e+01 4.88000000e+01 4.25200000e+01
 5.01000000e+01 1.68400000e+01 3.29600000e+01 3.22600000e+01
 2.10800000e+01 2.88400000e+01 4.96300000e+01 1.80900000e+01
 3.10800000e+01 2.66500000e+01 1.81400000e+01 1.94000000e+01
 1.49851565e+01 4.73300000e+01 7.10000000e+01 3.42600000e+01
 2.99838130e+01 1.49882300e+01 6.09300000e+01 4.91739968e+01
 2.81600000e+01 1.50500000e+01 3.29500000e+01 2.08000000e+01
 1.49832300e+01 2.49400000e+01 1.49959800e+01 3.01900000e+01
 7.85600000e+01 1.96700000e+01 2.56500000e+01 4.30200000e+01
 3.45700000e+01 1.49454947e+01 1.84500000e+01 3.14400000e+01
 1.60495072e+01 1.81500000e+01 2.37000000e+01 4.28300001e+01
 5.40492700e+01 2.50000000e+01 2.67600000e+01 1.34780000e+02
 1.64700000e+01 2.56000000e+01 7.08300000e+01 2.66900000e+01
 4.53700000e+01 7.51000000e+01 1.83600000e+01 5.16100000e+01
 2.95300000e+01 1.49921956e+01 3.42900000e+01 1.80600000e+01]

Values for  Loan/No Loan
[0 1]

In [15]:
# Checking set of values in all columns
for i in data2.columns:
    print("\nValues for ", i)
    print(data2[i].unique())

Values for  ID
[198980 167688 198768 ... 163156 169610 175557]

Values for  Asst_Reg
[1773284 5298273  189781 ... 1895531 2168910 4140268]

Values for  GGGrade
['II' 'VI' 'III' 'V' 'IV' 'I' 'VII']

Values for  Experience
['2yrs' '>10yrs' '4yrs' '9yrs' '1yrs' '<1yr' '3yrs' '5yrs' '8yrs' '7yrs'
 '6yrs']

Values for  Validation
['Source Verified' 'Vfied' 'Not Vfied']

Values for  Yearly Income
[140800.    146080.    202222.24  ... 263577.6   171508.48   96718.336]

Values for  Home Status
['OWN' 'MOR??AGE' 'REN?' 'NONE' 'OTHER']

Values for  Unpaid 2 years
[ 0  1  2  4  3  5  7 10 12 15  6  8 17  9 14 13 11 18]

Values for  Already Defaulted
[0 1 2 3]

Values for  Designation
['processor' 'Speech Language Pathologist' 'Raytheon' ...
 'Parade Performer' 'Sr. Chemistry Technician' 'ParaEducator']

Values for  Debt to Income
[16.9176 28.6944 51.156  ...  2.604  66.8808 64.9992]

Values for  Postal Code
[90600. 32300. 88000. 19900. 34900. 10400. 62000.    nan  3200. 65400.
 18600. 48000. 46000. 77000. 89100. 30300. 28400. 75000. 91700. 93900.
 67900. 93300. 97000. 62600. 10000. 80000. 91600.  7900. 18900. 47400.
  6400. 20600. 15600. 37000. 19100. 18000. 92500. 78500. 63100. 17600.
 11400. 76100. 54900. 31600. 84600. 78600. 90000. 75100. 38200. 60600.
 91300. 94500. 49500.  7100. 60400. 92000. 45200. 79900. 44600. 12100.
 33000. 33100. 93200. 27600. 55300. 78300. 14400. 21200. 36500.  8800.
 44800. 80200. 13600. 11100. 20700. 32700. 47000. 11200.  7000.  6700.
 44400. 28200. 30000. 33300. 85000. 43000. 98900. 37400. 43500. 38600.
 33400. 34200. 11300. 71200. 34600. 66200. 96700. 98000. 95100.  6600.
 26100. 30200. 78700. 70100. 21100. 97300.  3800. 73100. 16900. 40300.
 79400. 61200. 22700. 35100. 11500. 28600. 57100. 21000. 33500. 30100.
  1000. 45100.  6800. 75200. 85700. 46300. 27500. 34100. 93700. 46600.
 85200. 94100. 92100. 24700. 27200.  8000.  2000. 31000. 91900. 39200.
  2300. 24000. 60900. 27300. 24500. 10500. 19000. 63500. 95600. 28100.
  2400. 11700. 19700. 55000. 45300. 28000. 22100. 70000. 95400. 44700.
 78200. 33600. 68600. 63300.  2800.  6000. 85600. 84000. 44300. 85300.
 23400. 26000. 53000.  7700.  1900. 97200. 23200. 66000. 48300.  7600.
 12000. 95000. 54700. 76200. 98500. 22400. 88200. 33700. 20900. 12500.
 17300. 45500. 70500. 80400. 70400. 80100. 60000. 14000. 29900. 85500.
 20100. 15300. 32200. 99700. 30700. 17000. 44100. 72300. 89800. 92300.
 63400.  1300. 77300. 40200. 63000. 25700. 12200.  6300. 40000. 87500.
 72100. 32500. 49600. 76600. 61000. 77400. 65200. 48100. 14200. 31500.
 65500. 75700. 67800. 71100. 19600. 75400. 89400. 96800. 66700. 21800.
 88100. 89000. 73000. 78400. 19400. 48600. 92600. 49400.  2500. 53500.
  8300. 91200. 32400. 49000. 59900. 30500. 86300.  1400. 36400. 90700.
 19500. 28700. 71400. 37300. 33900. 25800. 98400. 10300. 70300.  1500.
 25300. 44500. 60500.  8600.  2100. 94700. 29500. 92800. 27400. 68800.
 46200. 95800. 29400. 65700. 23600. 32800. 23300. 90200. 98800. 95700.
 53200.  7800. 31900. 86400. 77500. 77900. 99200. 41000. 98100. 93600.
 94600. 47900. 32000.  1100. 11600. 93000. 33800. 57200. 74000. 92700.
 85100. 97100. 55100. 15200. 40600. 99300. 95300. 54100. 24100. 80500.
 91500. 84100. 90300. 30600. 57600. 29600. 94000. 23100. 87100. 54800.
 22500. 74100. 80900.  7200. 37100. 81600. 76000. 15000. 36200. 91000.
 20000. 48800.  7400. 10700. 91400. 53100. 72400. 47700. 76500. 93400.
 10900.  6500. 72200. 71000. 28500. 65800. 61400. 99000. 79100. 47200.
 18300. 95200. 22900.  5400. 15400. 64400. 43200. 21600. 76400. 10600.
 28300. 46100. 22600. 93500. 37200. 44200. 34400. 84400. 55400. 66900.
 14900. 35400. 75900. 13400. 23500. 83100. 16800. 58400. 43900. 78000.
 71300. 35600. 82800. 43100. 93100. 98200. 22300. 42200. 64000. 29700.
 84700. 77800. 71600. 20800. 78100. 62200. 14100. 14600. 75600. 67200.
 28900. 51300.  1700. 37700. 47800. 35000. 32900. 56300. 29300. 62500.
 13500.  8700. 25400. 92200. 13700. 59000. 71900. 18400. 22000. 49700.
 73500. 96100. 62700. 96000. 60100. 79700.  1800. 26500.  1200. 88300.
 44900. 70600. 15500. 31200. 44000. 37900. 91100. 48500. 98600. 90800.
 82000. 27100. 13000.  2600. 27000.  8900. 60800. 87000. 72600. 48700.
 97400. 35200. 38300.  2700.  8500. 26300. 76800. 79600. 42600. 94900.
 17400. 15800. 45800. 17900. 67000. 79000. 19300. 21700. 16200. 27800.
  1600. 70800. 36100. 84300. 80600. 31700. 94800. 81000. 66600. 90500.
 66500. 11000. 23000. 29800. 29100. 68100. 46800. 97700. 53900. 48200.
 65000. 62900. 17200. 70700. 99800.  2900. 72000. 87400. 35800. 13800.
 76300. 36600. 38000. 13100.  3000. 75800.  3400. 46500. 42700. 30800.
 16000. 99600. 55900. 98300. 25500.  3700. 59200. 74800. 83000.  7300.
 37600. 41100. 36000. 56700. 35500. 67400. 95900. 34700. 38100. 56000.
 15100. 63600. 63900. 38900. 81300. 32600. 64100. 74700. 57400.  3100.
  7500. 47300.  5600. 91800. 65600. 17800. 39100.  8100. 12900. 14500.
 97900. 45600. 42500.  6200. 32100.  6100. 40700.  4600. 36700. 46400.
 56400. 45000. 18800. 37800. 21400. 86000. 57300. 29200. 39000. 23800.
 89500. 73700. 94400. 74900. 30900. 59100. 89300. 97800. 75500. 61500.
 12800. 48400. 56100. 71800. 12600. 72800. 64700. 72900. 21900. 39600.
 43600. 14800. 27900. 24200. 77600. 17700. 49100. 43400. 54400. 13900.
 66100. 61600. 56500. 81500. 62300. 54300. 13200.  4200. 99500. 79200.
 18200. 56600. 61100. 36300. 57000. 24300. 59800.  8200. 40500. 49800.
 27700. 22200. 78900. 29000. 82700. 89700. 31300. 61300. 17500. 16500.
 54600. 53700. 99100. 97500. 40400. 12700. 30400. 66800. 14300. 10800.
 67300. 68000. 40100. 72700. 61800. 61700. 74400. 46700. 13300. 45400.
 28800. 11900. 54000. 39500. 35700. 85900. 14700. 87300. 80800. 12300.
 62400. 19800. 74300.  5800. 43300. 41200. 81400. 88400. 64800. 16400.
 62800. 38800. 22800. 11800. 47100. 39400. 49300. 79500.  4800. 36800.
 99400. 72500. 16700. 55700. 76700. 49900. 67100. 67500. 66400. 90400.
 71700. 48900. 18500. 43700. 54500.  4400. 43800. 18100. 81100. 86500.
 25000. 40800. 55800. 78800. 49200. 25100. 31400. 59600. 23700. 35900.
 59700. 45700. 38500. 60300. 42300. 39300. 17100. 73400. 95500. 16100.
  2200. 46900. 82900. 47500. 31100. 75300. 42100. 63700. 12400. 25200.
 24600. 15700.  3300.  6900. 40900. 42000. 74600. 60700. 82300.  3600.
 64600. 21500. 76900. 99900. 38400. 81200. 24400. 65100.  5000. 92400.
 80300. 25900. 64500. 59400. 57700. 58200. 18700. 56200. 87900. 82600.
 65300. 59300. 82500. 24800. 68900. 69300. 77700. 67700. 87800. 42400.
  4900. 73800. 79300. 39800. 60200. 15900. 26700. 16300. 47600. 16600.
  3500. 26200. 69100.  4000. 68500.  5200. 41300. 59500. 94300.  9000.
 39700. 96300. 26400.  5700. 74500. 63800. 53400. 58000. 10100. 25600.
 68400. 87700. 31800. 97600. 41700. 10200.  5300. 67600. 41500. 79800.
  9800.  8400. 58700.  5100. 80700. 26800. 58600. 58100. 83500. 23900.
 73600. 84500. 82400. 61900. 54200. 24900. 58800. 58500.  4500. 53800.
 26600. 41800.  4100. 38700. 26900. 68700. 82200. 77200. 57500. 20400.]

Values for  Lend Amount
[17955.   59850.   19323.   ... 14406.75 45015.75 58011.75]

Values for  Deprecatory Records
[ 0  1  2  4  3  6  5  8 21 11 12  9  7 13 10]

Values for  Interest Charged
[ 8.88 10.1  19.3  ... 15.13 19.9  13.28]

Values for  Usage Rate
[ 78.432  76.368 157.552 ... 179.396 198.832 186.62 ]

Values for  Inquiries
[1 2 0 5 3 4 6]

Values for  Present Balance
[ 59769.3  532962.13 288816.48 ... 614710.3  107614.8  783477.16]

Values for  Gross Collection
[0.000000e+00 1.029690e+03 1.765770e+03 2.181290e+03 6.785200e+02
 1.210000e+01 2.969660e+03 1.575420e+03 2.799450e+03 1.970800e+03
 1.148170e+03 3.116980e+03 1.345020e+03 3.278140e+03 1.086100e+02
 3.543000e+02 7.228800e+02 1.111000e+01 5.385300e+02 1.176000e+01
 6.392220e+03 4.946100e+02 1.213170e+03 2.803200e+02 4.542260e+03
 5.585470e+03 1.911420e+03 3.877970e+03 1.488270e+03 2.742900e+02
 1.900000e+01 6.738800e+02 1.675630e+03 2.663010e+03 2.940060e+03
 7.089900e+02 2.039970e+03 1.958450e+03 6.086910e+03 1.732910e+03
 1.319220e+03 1.064580e+03 9.492700e+02 1.590830e+03 7.107510e+03
 7.918200e+02 2.337220e+03 6.125500e+02 1.081630e+03 6.966800e+02
 1.487130e+03 2.567180e+03 5.756200e+02 3.216250e+03 2.685490e+03
 1.772740e+03 2.654320e+03 8.207960e+03 1.722380e+03 1.025150e+03
 2.097900e+03 5.572200e+03 2.639410e+03 1.328040e+03 6.955400e+02
 1.060620e+03 3.934770e+03 9.590100e+02 2.233930e+03 2.567210e+03
 1.570340e+03 3.051700e+02 2.196420e+03 6.600400e+02 1.102660e+03
 1.844330e+03 1.734230e+03 6.982400e+02 7.658700e+02 1.748920e+03
 1.845930e+03 1.074450e+03 3.448700e+02 2.568210e+03 1.196640e+03
 1.568200e+03 1.672660e+03 8.152700e+02 7.654900e+02 1.120000e+01
 5.084800e+02 2.925110e+03 3.900730e+03 1.337400e+03 2.340300e+03
 1.155000e+01 2.295910e+03 2.467490e+03 1.570500e+02 3.445930e+03
 1.136080e+03 1.054030e+03 8.071800e+02 3.721510e+03 3.629560e+03
 1.073100e+03 1.390000e+04 1.618090e+03 9.613200e+02 6.356600e+02
 1.062000e+01 1.842240e+03 8.270300e+02 2.041820e+03 9.792500e+02
 3.192870e+03 2.000000e+01 4.399400e+02 4.167560e+03 1.875250e+03
 2.028100e+02 2.435920e+03 9.621900e+02 1.682110e+03 4.930300e+02
 1.484020e+03 4.037680e+03 2.095250e+03 1.560190e+03 6.073000e+02
 2.679840e+03 1.625400e+03 2.486400e+02 5.086260e+03 5.370300e+02
 6.346300e+02 5.669860e+03 2.121290e+03 1.959550e+03 6.921400e+02
 1.014540e+03 1.894390e+03 9.434700e+02 1.645100e+02 5.454300e+02
 1.332330e+03 1.292010e+03 2.323570e+03 2.489070e+03 1.297050e+03
 2.560860e+03 1.197269e+04 3.590150e+03 3.365040e+03 2.825460e+03
 4.708800e+02 9.714300e+02 6.413200e+02 3.200700e+02 1.233200e+02
 1.651200e+03 3.152520e+03 2.212820e+03 3.067680e+03 1.600410e+03
 1.095960e+03 1.839700e+03 1.347420e+03 7.236300e+02 8.157300e+02
 1.574600e+02 6.939120e+03 1.113180e+03 8.830800e+02 1.337790e+03
 1.014520e+03 2.624900e+02 3.703190e+03 5.258270e+03 3.136710e+03
 1.309320e+03 1.800000e+01 1.382160e+03 1.013030e+03 1.558340e+03
 1.285381e+04 2.835000e+02 4.152940e+03 1.866870e+03 2.253760e+03
 3.615900e+02 2.869350e+03 1.945570e+03 1.295120e+03 1.521000e+01
 3.659190e+03 9.310600e+02 4.131080e+03 2.800000e+02 1.011960e+03
 3.218310e+03 2.660970e+03 3.539000e+03 4.143590e+03 3.223600e+02
 3.649090e+03 1.782510e+03 1.044000e+01 3.198770e+03 1.232000e+01
 1.283820e+03 7.924200e+02 1.065690e+03 2.064060e+03 4.066400e+02
 3.833660e+03 1.916780e+03 4.633140e+03 8.193100e+02 5.918400e+02
 1.433540e+03 2.093220e+03 6.983400e+02 2.931360e+03 5.779400e+02
 1.974600e+03 2.703680e+03 1.472370e+03 4.387700e+02 2.018900e+02
 2.659950e+03 1.254120e+03 2.852440e+03 5.183400e+02 1.360000e+01
 6.744200e+02 2.152080e+03 4.820600e+02 6.513900e+02 5.936290e+03
 6.406770e+03 1.616350e+03 4.877960e+03 7.038600e+03 1.225550e+03
 2.198170e+03 2.461420e+03 3.398090e+03 2.040000e+02 1.324840e+03
 5.344760e+03 2.507390e+03 1.548740e+03 8.660800e+02 4.980300e+02
 3.176490e+03 5.988550e+03 1.126050e+03 3.250000e+03 3.781520e+03
 2.902740e+03 4.652700e+02 3.453160e+03 5.702800e+02 6.712360e+03
 3.988130e+03 4.101320e+03 5.066200e+02 1.466240e+03 1.667380e+03
 1.046430e+03 2.022710e+03 3.341860e+03 1.239740e+03 4.350070e+03
 3.768060e+03 1.793000e+01 4.619480e+03 6.943300e+02 9.353600e+02
 2.327260e+03 5.460900e+03 1.766910e+03 3.529160e+03 3.000660e+03
 1.899290e+03 4.324820e+03 3.866060e+03 2.182450e+03 1.534730e+03
 1.859060e+03 1.381500e+03 2.333410e+03 8.612970e+03 1.333900e+03
 1.718600e+03 3.604680e+03 7.559500e+02 6.955100e+02 2.705520e+03
 1.021680e+03 9.446600e+02 2.234580e+03 8.285700e+02 9.345300e+02
 3.790220e+03 1.270490e+03 6.617500e+02 1.465660e+03 1.720000e+01
 2.006700e+02 2.217600e+03 4.290250e+03 9.705600e+02 8.822400e+02
 4.040270e+03 3.936400e+02 1.708130e+03 2.058000e+01 4.473930e+03
 3.646730e+03 5.909300e+02 1.619470e+03 9.795600e+02 5.529000e+01
 2.200000e+03 2.329000e+01 3.065440e+03 1.187220e+03 1.172960e+03
 1.588430e+03 3.015810e+03 4.557400e+02 2.444000e+03 2.093290e+03
 2.417150e+03 6.069700e+02 4.920090e+03 2.678790e+03 6.757900e+02
 1.177070e+03 1.910000e+03 1.958100e+02 2.146260e+03 4.728910e+03
 1.734330e+03 5.322800e+02 2.500000e+02 1.303470e+03 1.760770e+03
 2.552900e+02 5.371000e+02 4.809360e+03 2.100000e+01 9.039700e+02
 8.303740e+03 9.031200e+02 9.478300e+02 4.297300e+03 1.353710e+03
 4.186300e+03 6.973100e+02 6.493600e+02 1.634560e+03 1.326750e+03
 1.320900e+03 1.170920e+03 3.282480e+03 7.424000e+02 3.418100e+02
 6.459610e+03 1.042360e+03 3.403500e+02 7.859100e+02 6.845700e+02
 1.085600e+03 6.122600e+02 1.988340e+03 2.124100e+03 1.804840e+03
 2.372640e+03 1.480450e+03 6.851100e+02 3.894480e+03 2.963530e+03
 1.528390e+03 8.258700e+02 1.347450e+03 1.721960e+03 1.000970e+03
 1.470150e+03 3.594610e+03 7.668860e+03 1.144000e+01 1.759570e+03
 8.659300e+02 2.438450e+03 2.986680e+03 6.148600e+02 3.605340e+03
 5.864500e+02 3.289520e+03 2.306410e+03 4.798900e+02 1.186900e+03
 1.618060e+03 2.815960e+03 2.522650e+03 4.192100e+02 1.382420e+03
 2.903400e+02 3.233400e+02 3.161000e+02 1.200000e+03 1.189800e+02
 6.885700e+02 1.815300e+03 5.621130e+03 1.706280e+03 1.607510e+03
 1.723470e+03 4.128700e+03 5.560400e+02 3.506960e+03 1.478000e+01
 2.068030e+03 1.404070e+03 4.708790e+03 1.767520e+03 3.001220e+03
 2.569480e+03 1.545650e+03 7.020600e+02 2.291020e+03 2.207480e+03
 1.362020e+03 7.533700e+02 2.162110e+03 4.675950e+03 3.256310e+03
 7.132500e+02 1.795540e+03 9.679000e+02 1.460470e+03 1.441260e+03
 7.431600e+02 1.634420e+03 2.771140e+03 4.306330e+03 1.853000e+01
 2.752480e+03 4.839860e+03 6.719500e+02 1.920000e+01 9.065500e+02
 2.291550e+03 5.963970e+03 1.266010e+03 1.010250e+03 6.616000e+02
 3.911220e+03 2.088070e+03 1.779170e+03 1.897240e+03 7.414000e+02
 7.837200e+02 1.578520e+03 7.035200e+02 2.774400e+02 5.073200e+02
 2.337290e+03 1.343530e+03 1.318060e+03 2.098470e+03 1.605060e+03
 3.589700e+02 1.157250e+03 2.620910e+03 3.820080e+03 4.489300e+02
 1.023450e+03 5.885000e+02 8.807800e+02 3.519960e+03 8.622600e+02
 2.840440e+03 1.645840e+03 6.410000e+02 5.026110e+03 6.441700e+02
 6.182610e+03 2.001970e+03 8.404700e+02 1.641150e+03 2.253940e+03
 1.089580e+03 3.009270e+03 2.352620e+03 7.045700e+02 1.503800e+03
 2.120560e+03 2.629010e+03 1.925640e+03 4.261300e+02 4.754980e+03
 9.043000e+02 6.057840e+03 2.346180e+03 2.506870e+03 1.420290e+03
 3.377010e+03 2.258630e+03 4.027540e+03 2.365920e+03 4.169100e+02
 1.878740e+03 1.826080e+03 5.687500e+02 1.600890e+03 1.302250e+03
 5.346500e+02 3.169930e+03 2.060950e+03 3.059550e+03 7.009200e+02
 1.400900e+02 4.776600e+02 5.344000e+01 1.242320e+03 1.017880e+03
 4.650100e+02 1.878830e+03 1.219770e+03 1.361130e+03 2.252480e+03
 5.067500e+02 1.670210e+03 1.998550e+03 2.000000e+02 1.228640e+03
 1.576660e+03 4.636800e+02 3.300230e+03 7.475600e+02 7.722200e+02
 2.500000e+03 2.854720e+03 6.321770e+03 3.093180e+03 2.733140e+03
 3.272010e+03 1.570190e+03 5.771400e+02 1.950000e+03 6.126500e+02
 3.839180e+03 5.854400e+02 1.000000e+02 3.883090e+03 2.668750e+03
 2.177990e+03 3.780590e+03 1.898940e+03 1.564740e+03 2.760670e+03
 2.434650e+03 2.045040e+03 3.105500e+03 4.000000e+01 1.193200e+03
 6.520000e+02 4.707900e+02 2.780360e+03 1.195490e+03 1.458000e+01
 3.429030e+03 2.021110e+03 1.134990e+03 1.018170e+03 2.618630e+03
 3.030730e+03 8.198700e+02 1.433360e+03 8.375200e+02 3.171850e+03
 1.329040e+03 2.336440e+03 5.158300e+02 2.260210e+03 4.142840e+03
 3.786170e+03 7.395330e+03 1.690030e+03 2.600600e+03 9.970900e+02
 5.137340e+03 1.349290e+03 8.720900e+02 1.855520e+03 2.651670e+03
 2.916610e+03 1.001480e+03 3.036570e+03 3.281170e+03 1.546430e+03
 2.058690e+03 4.356830e+03 9.012600e+02 5.189000e+02 4.479800e+02
 9.837400e+02 8.615500e+02 1.626400e+03 1.675600e+02 3.675020e+03
 2.574100e+02 2.054560e+03 4.082170e+03 4.619200e+03 1.157290e+03
 3.291970e+03 8.416400e+02 7.755300e+02 1.184950e+03 4.216930e+03
 9.538500e+02 2.809400e+02 1.499670e+03 2.389040e+03 1.059160e+03
 2.232890e+03 1.656190e+03 1.195420e+03 1.702530e+03 1.333770e+03
 6.107150e+03 1.122070e+03 1.514610e+03 4.435110e+03 3.123420e+03
 4.722580e+03 2.787540e+03 8.656600e+02 3.642200e+02 1.851160e+03
 2.764600e+02 4.146500e+02 3.045200e+02 2.185300e+03 1.222590e+03
 4.550730e+03 1.147120e+03 4.024000e+03 5.536500e+02 3.670600e+03
 4.191700e+02 2.830020e+03 2.188080e+03 6.576930e+03 1.111400e+03
 6.271600e+02 1.796010e+03 2.770400e+02 2.660770e+03 5.579710e+03
 2.413050e+03 1.646410e+03 2.485990e+03 2.639640e+03 3.087770e+03
 6.052100e+02 3.713300e+02 7.810300e+02 2.908580e+03 7.846900e+02
 1.531370e+03 1.713540e+03 9.970440e+03 1.027400e+03 6.039600e+02
 2.510080e+03 1.936680e+03 9.067100e+02 1.862480e+03 3.647900e+03
 5.890600e+02 3.593980e+03 7.936200e+02 6.670500e+02 2.652270e+03
 1.027190e+03 1.371570e+03 2.264230e+03 1.563580e+03 1.347240e+03
 5.361000e+02 1.380720e+03 5.182400e+03 1.346780e+03 1.013660e+03
 1.835860e+03 3.152220e+03 3.954500e+02 6.908600e+02 5.959200e+02
 1.233990e+03 1.339280e+03 7.385100e+02 1.501000e+02 1.370700e+03
 5.935600e+03 3.177760e+03 2.792860e+03 1.197770e+03 1.693230e+03
 2.460590e+03 2.262610e+03 1.938830e+03 4.218830e+03 2.012990e+03
 1.367810e+03 8.887700e+02 1.434550e+03 2.989190e+03 7.540200e+02
 3.038600e+02 1.375500e+03 1.159310e+03 2.744490e+03 1.632000e+01
 2.982950e+03 1.516380e+03 5.437500e+02 5.785200e+02 2.135050e+03
 2.769360e+03 2.490110e+03 5.000000e+02 1.582630e+03 3.480550e+03
 3.861100e+03 8.621100e+02 9.950000e+02 3.545370e+03 7.817400e+02
 4.641350e+03 2.030000e+01 1.194860e+03 1.194290e+03 1.265160e+03
 1.500000e+01 5.285500e+02 2.320930e+03 8.962000e+01 1.274570e+03
 1.279470e+03]

Values for  Sub GGGrade
[17 19 37 25 21 18 31 29 28 24 36 11 34 20 22 27 33 16 14 26 23 30 13 15
 32 12 44 41 39 35 43 38 40 42 45]

Values for  File Status
['fully paid' 'whole']

Values for  State
['California' 'Florida' 'NM' 'DE' 'Newyork' 'IL' 'GA' 'NH' 'MO' 'PA' 'MI'
 'IN' 'TX' 'NV' 'NC' 'KS' 'OR' 'CO' 'NewJersey' 'CT' 'Maryland' 'TN' 'WI'
 'UT' 'Ohio' 'MN' 'AL' 'AZ' 'WA' 'MS' 'LA' 'HI' 'WV' 'OK' 'KY' 'VA' 'SD'
 'MA' 'NE' 'RI' 'SC' 'AK' 'AR' 'MT' 'DC' 'VT' 'WY' 'ND' 'ME']

Values for  Account Open
[23 17 15 18  7 16 22 14 10 11  6 13 30  8  5 19  9 21 31 28 29 20 37 12
 25 26 24 35  4 27 32  3  2 33 49 34 36 40 41 51 38 39 42 43 46 52 44 54
 60 48 47]

Values for  Total Unpaid CL
[ 33532.   149234.    70218.   ...  54092.76 223436.   166996.  ]

Values for  Duration
['3 years' '5 years']

Values for  Unpaid Amount
[15755.94 68237.55 66272.76 ...  5384.79 57683.43  2783.88]

Values for  Reason
['major  purchase' 'debt  consolidation' 'credit  card' 'other'
 'home  improvement' 'house' 'medical' 'small  business' 'vacation'
 'moving' 'car' 'wedding' 'renewable  energy']

Values for  Claim Type
['I' 'J']

Values for  Due Fee
[  0.          15.          20.          37.65        57.71
  37.18        25.63        33.05        31.66        30.
 113.18        66.72858     25.96        59.8         15.4
  43.62        22.3         20.21        14.99846     32.61
  20.34        44.03        45.          43.59        33.27
  17.8         16.61        60.          33.45        47.22
  52.14        21.47        39.33        18.93        24.9
  31.2         40.68        30.137       37.27        77.91
  18.09000002  31.47        27.34        20.08        18.12
  19.07        16.71        18.38        79.38        35.46
  14.98139471  18.69        24.51        34.82        17.41439
  31.07        32.76        27.39        31.85        18.02900011
  29.98774     25.36        39.59        17.74        16.07
  19.15        31.44        16.4        131.49        11.97
  30.88        58.38        24.02        41.2         17.04
  17.77        47.16        28.78        19.11        66.09
  32.29        60.89207978  21.06        16.29        27.03
  29.02        19.82        27.89       100.38        19.97000001
  50.49        22.93        50.31        45.18        31.06
  22.71        31.52        40.29        33.24        63.49
  16.56        20.28        20.5         28.12        43.63999997
  26.22        28.68        15.32        33.76        19.69
  19.79        61.19        20.8         15.19        14.95911693

In [16]:
# Checking for data imbalance
data1["Loan/No Loan"].value_counts()

0    70988
1    16512
Name: Loan/No Loan, dtype: int64

Data is highly imbalanced

In [17]:
# Dropping irrelevant columns
df1 = data1.drop(["GGGrade", "Sub GGGrade", "Postal Code", "Designation"], axis = 1)
df2 = data2.drop(["GGGrade", "Sub GGGrade", "Postal Code", "Designation"], axis = 1)

In [18]:
df1["Home Status"] = df1["Home Status"].replace("MOR??AGE", "MORTGAGE")
df1["Home Status"] = df1["Home Status"].replace("REN?", "RENT")

df2["Home Status"] = df2["Home Status"].replace("MOR??AGE", "MORTGAGE")
df2["Home Status"] = df2["Home Status"].replace("REN?", "RENT")

In [19]:
df1.describe()

,ID,Asst_Reg,Yearly Income,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,Deprecatory Records,Interest Charged,Usage Rate,Inquiries,Present Balance,Gross Collection,Account Open,Total Unpaid CL,Unpaid Amount,Due Fee,Loan/No Loan
count,87500.00000,87500.00000,81925.00000,87500.00000,87500.00000,84011.00000,87500.00000,87500.00000,87500.00000,87500.00000,87500.00000,87500.00000,87500.00000,87500.00000,83314.00000,82648.00000,87500.00000,87500.00000
mean,83946.25351,3798914.12415,134859.62978,0.33294,0.00573,30.94266,25920.53568,0.20240,16.51837,95.51735,0.67064,236389.46478,39.46170,12.77944,53268.64039,29556.49452,0.31641,0.18871
std,36100.10295,2289038.08259,98824.72556,0.87608,0.08350,14.07981,14433.83721,0.64641,4.90201,40.55404,0.95957,255056.78191,391.91958,5.37116,53255.51391,37456.24506,3.54609,0.39128
min,21560.00000,24847.00000,8800.00000,0.00000,0.00000,0.00000,1710.00000,0.00000,8.00000,0.00000,0.00000,0.00000,0.00000,2.00000,332.00000,0.00000,0.00000,0.00000
25%,52616.75000,1483874.25000,83246.59200,0.00000,0.00000,20.42880,15048.00000,0.00000,12.31000,66.04800,0.00000,51734.93000,0.00000,9.00000,23240.00000,11446.74000,0.00000,0.00000
50%,83900.00000,4132010.50000,114400.00000,0.00000,0.00000,30.13920,23940.00000,0.00000,16.49000,97.00800,0.00000,138806.22500,0.00000,12.00000,39674.00000,20892.78000,0.00000,0.00000
75%,115261.25000,5952908.75000,160160.00000,0.00000,0.00000,40.90800,34200.00000,0.00000,20.77000,126.59200,1.00000,353475.54000,0.00000,16.00000,66400.00000,36449.07750,0.00000,0.00000
max,146559.00000,7351847.00000,8264030.72000,18.00000,6.00000,639.29040,59850.00000,86.00000,25.00000,1534.75600,8.00000,5629234.33000,26308.47000,83.00000,1710630.00000,1338777.81000,169.05000,1.00000

In [20]:
df2.describe()

,ID,Asst_Reg,Yearly Income,Unpaid 2 years,Already Defaulted,Debt to Income,Lend Amount,Deprecatory Records,Interest Charged,Usage Rate,Inquiries,Present Balance,Gross Collection,Account Open,Total Unpaid CL,Unpaid Amount,Due Fee
count,37500.00000,37500.00000,35075.00000,37500.00000,37500.00000,35989.00000,37500.00000,37500.00000,37500.00000,37500.00000,37500.00000,37500.00000,37500.00000,37500.00000,35686.00000,35431.00000,37500.00000
mean,184143.86797,3804857.79483,134030.83240,0.33643,0.00531,30.91903,25828.00416,0.20008,16.51101,95.25911,0.67664,235352.80234,39.48407,12.77779,53448.19734,29280.65881,0.30979
std,21683.22439,2284114.95103,100084.49663,0.88764,0.07797,13.87167,14402.06179,0.56314,4.91259,40.49322,0.96452,254309.73318,364.11458,5.36053,52154.82990,35608.49292,3.39632
min,146560.00000,37522.00000,8800.00000,0.00000,0.00000,0.00000,1710.00000,0.00000,8.00000,0.00000,0.00000,0.00000,0.00000,2.00000,332.00000,0.00000,0.00000
25%,165341.25000,1495828.50000,84194.00000,0.00000,0.00000,20.47920,14919.75000,0.00000,12.25000,65.53200,0.00000,51295.72000,0.00000,9.00000,23240.00000,11414.25000,0.00000
50%,184257.00000,4134009.50000,114400.00000,0.00000,0.00000,30.18960,23811.75000,0.00000,16.51500,96.49200,0.00000,138379.54000,0.00000,12.00000,39508.00000,20680.74000,0.00000
75%,202869.25000,5934897.75000,158400.00000,0.00000,0.00000,40.72320,34200.00000,0.00000,20.77000,126.76400,1.00000,351498.26000,0.00000,15.00000,66400.00000,36184.45500,0.00000
max,221557.00000,7351969.00000,8800000.00000,18.00000,3.00000,116.50800,59850.00000,21.00000,25.00000,254.56000,6.00000,4909890.18000,13900.00000,60.00000,1475408.00000,1535829.66000,131.49000

In [21]:
up_quan = df1["Yearly Income"].quantile(.75)
low_quan = df1["Yearly Income"].quantile(.25)
low_bound = 1.5 * low_quan
up_bound = 1.5 * up_quan
index_names = df1[ (df1['Yearly Income'] < low_bound) | (df1['Yearly Income'] > up_bound) ].index
df1.drop(index_names, inplace = True)
low_bound, up_bound, index_names

(124869.888,
 240240.0,
 Int64Index([    0,     1,     2,     3,     4,     6,    10,    13,    14,
                15,
             ...
             87484, 87486, 87489, 87490, 87493, 87494, 87495, 87496, 87497,
             87498],
            dtype='int64', length=52951))

In [22]:
df1.isnull().sum()

ID                        0
Asst_Reg                  0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         1359
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        1684
Duration                  0
Unpaid Amount          1903
Reason                    0
Claim Type                0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [23]:
df2.isnull().sum()

ID                        0
Asst_Reg                  0
Experience                0
Validation                0
Yearly Income          2425
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         1511
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        1814
Duration                  0
Unpaid Amount          2069
Reason                    0
Claim Type                0
Due Fee                   0
dtype: int64

In [24]:
df1[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']] = df1[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].fillna(df1[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].median())
df2[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']] = df2[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].fillna(df2[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].median())

In [25]:
stru = {
        "Experience" : {"<1yr": 0, "1yrs": 1, "2yrs": 2, "3yrs": 3, "4yrs": 4, "5yrs": 5, "6yrs": 6, "7yrs": 7, "8yrs": 8, "9yrs": 9, ">10yrs": 10 },
        "Validation" : {"Not Vfied": 0, "Vfied": 1, "Source Verified": 2},
        "Home Status" : {"NONE": 0, "RENT": 1,"MORTGAGE": 2, "OWN": 3, "OTHER": 4},
        "File Status" : {"whole": 0, "fully paid": 1},
        "Duration" : {"3 years": 0, "5 years": 1},
        "Claim Type" : {"I": 0, "J": 1}
        }

# Columns for One Hot Encoding

oneHotCols=["State", "Reason"]

# Performing Label Encoding

df1 = df1.replace(stru)
df2 = df2.replace(stru)


# Performing One Hot Encoding

df1 = pd.get_dummies(df1, oneHotCols)
df2 = pd.get_dummies(df2, oneHotCols)

## 2 Exploratory Data Analyis

In this section you can talk about the plots and the insights you have generated from the data

## 3 Feature Engineering

In this section you can implement the feature engineering techniques for dimensionality reduction

In [26]:
# Train-test Split
from sklearn.model_selection import train_test_split

x = df1.drop("Loan/No Loan", axis = 1)
y = df1["Loan/No Loan"]

x_tr, x_val, y_tr, y_val = train_test_split(x, y, test_size = .3, random_state = 9)

In [27]:
x_tr = x_tr.astype("float32")
x_val = x_val.astype("float32")
y_tr = y_tr.astype("float32")
y_val = y_val.astype("float32")

In [28]:
# Balancing Classes
from imblearn.over_sampling import SMOTE
sm = SMOTE(sampling_strategy = 1 ,k_neighbors = 15)   #Synthetic Minority Over Sampling Technique
x_tr_res, y_tr_res = sm.fit_resample(x_tr, y_tr.ravel())

In [29]:
# Applying PCA
from sklearn.decomposition import PCA as RandomizedPCA

n_components = 50              # extracting 50 most important features
pca = RandomizedPCA(n_components=n_components).fit(x_tr_res)
x_train_pca = pca.transform(x_tr_res)
x_test_pca = pca.transform(x_val)

In [30]:
# Scaling Data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train_pca)
x_tr = sc.transform(x_train_pca)
x_val = sc.transform(x_test_pca)

## 4 Modelling + HyperParameter Tuning

In this you can build various ML models and try tuning the parameters involved to achieve better score

## Model 1

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV

lr = LogisticRegression(max_iter = 400)

param_lr = {"solver" : ["newton-cg", "lbfgs", "liblinear"]}

gs_lr = GridSearchCV(lr, param_lr, cv=10)

gs_lr.fit(x_tr, y_tr_res)
print(gs_lr.score(x_tr, y_tr_res))
lr_pr = gs_lr.predict(x_val)
print("F1 Score: ", f1_score(y_val,lr_pr))

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')

0.755834829443447
F1 Score:  0.5262072521051727

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')

In [32]:
from sklearn.neighbors import KNeighborsClassifier

#knn = KNeighborsClassifier()

#param_knn = {"n_neighbors": range(3,11),
#            "weights" : ["uniform", "distance"],
#             "algorithm" : ["auto", "ball_tree", "kd_tree", "brute"]}

gs_knn = KNeighborsClassifier(n_neighbors = 15, weights = "uniform", algorithm = "auto")
gs_knn.fit(x_tr, y_tr_res)
knn_pr = gs_knn.predict(x_val)
print(gs_knn.score(x_val, y_val))
print(f1_score(y_val, knn_pr))

0.6878919440424506
0.4163810211077034

In [33]:
from sklearn import svm
gs_svm = svm.SVC(C = 3, gamma = .3, kernel = "rbf" ) 
#param_grid = {"C": range(1, 11),
#              "gamma": [0.3, 0.4, 0.5],
#              "kernel": ["rbf", "poly", "sigmoid", "linear"]}

#gs_svm = GridSearchCV(clf, param_grid, cv=10)

gs_svm.fit(x_tr, y_tr_res)
svm_pr = gs_svm.predict(x_val)
print(gs_svm.score(x_val, y_val))
print(f1_score(y_val, svm_pr))

0.8060781476121563
0.09459459459459459

In [34]:
from sklearn.tree import DecisionTreeClassifier
gs_dt = DecisionTreeClassifier(criterion = "gini", max_depth = 12)

#param_dt = {"criterion" : ["gini", "entropy"],
#             "max_depth" : [11, 12, 13]}
#gs_dt = GridSearchCV(dt, param_dt, cv=10)
gs_dt.fit(x_tr, y_tr_res)
dt_pr = gs_dt.predict(x_val)
print(gs_dt.score(x_val, y_val))
print(f1_score(y_val, dt_pr))

0.704003859141341
0.44800287873335737

In [35]:
from sklearn.ensemble import RandomForestClassifier

gs_rf = RandomForestClassifier(criterion = "gini", max_depth = 12, n_estimators = 60)

#param_rf = {"criterion" : ["gini", "entropy"],
#             "max_depth" : range(1, 15),
#           "n_estimators" : [10, 20, 30, 40, 50, 60]}
#gs_rf = GridSearchCV(rf, param_rf, cv=10)
gs_rf.fit(x_tr, y_tr_res)
print(gs_rf.score(x_val, y_val))
rtr_pr = gs_rf.predict(x_val)
print(f1_score(y_val, rtr_pr))

0.7579353593825374
0.5185185185185185

In [41]:
df2 = df2.drop("Loan/No Loan", axis = 1)
x_test = pd.DataFrame(df2)
x_test.head()
x_test = pca.transform(x_test)
x_test = sc.transform(x_test)
x_test = pd.DataFrame(x_test)
x_test = x_test.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
test_pre = gs_lr.predict(x_test)

In [42]:
df2["Loan/No Loan"] = test_pre

In [43]:
df = pd.DataFrame(df2[["ID","Loan/No Loan"]])

In [44]:
df.to_csv("res.csv", index = False)

## Model 2 - Best Model

## Model 3